package com.danaga.exception.product;

public enum ProductSuccessMsg implements ProductMsgInterface{
	ADD_RECENTVIEW, REMOVE_MY_RECENTVIEWS, REMOVE_RECENTVIEW, REMOVE_OLD_RECENTVIEWS, FIND_MY_RECENTVIEWS,
	TOP_CATEGORY, CHILDREN_CATEGORY, ADD_CATEGORY, UPDATE_CATEGORY, REMOVE_CATEGORY, 
	TAP_HEART, UNTAP_HEART, REMOVE_MY_INTERESTS, 
	FIND_OPTIONSET_BY_ID, UPLOAD_PRODUCT, FIND_OPTION_NAME_VALUES, FOUND_NO_OTHER_OPTIONSETS, FIND_OTHER_OPTIONSETS, SEARCH_PRODUCTS, UPDATE_OPTIONSET, REMOVE_OPTION, REMOVE_OPTIONSET, REMOVE_PRODUCT, IS_MY_INTEREST, MY_INTERESTS, UPDATE_OPTION
	
	
}
